### PR TITLE
fixed output arrow

### LINKED ISSUE #258: New arrow to show that output is passed to next step after rollout/parrallel
## Description
Arrow printing should also show merging arrow after rollout/parallel. 
Example:
```python
m = (plus_one+plus_one) >> plus_one

Compose:

      └──────────┐
      │          │
      ▼ x        ▼ x
   0: plus_one + plus_one
      │
      ▼ x
   1: plus_one
```
## Solution
Something along this line would be great to make it clear that output is passed to next step
```
Compose:

      └──────────┐
      │          │
      ▼ x        ▼ x
   0: plus_one + plus_one
      │          │
      |    |──────
      ▼ x  ▼ x
   1: plus_one
```

### PR DESCRIPTION
**Pull request by jasonkhadka**
## Description

Fixes #258 
```
t = plus_out3 >> m1 / m2 / m2>> plus

Compose - "t":

      │
      ▼ x
   0: plus_out3         
      ││└───────────────────────────────────────┐
      │└───────────────────┐                    │
      │                    │                    │
      ▼ arg                ▼ arg                ▼ arg
   1: multiply(factor=2) / multiply(factor=2) / multiply(factor=2)
      │____________________│                    │
      │_________________________________________│ 
      │
      ▼ a
   2: plus  

```

previous output:
```
Compose - "t":

      │
      ▼ x
   0: plus_out3         
      ││└───────────────────────────────────────┐
      │└───────────────────┐                    │
      │                    │                    │
      ▼ arg                ▼ arg                ▼ arg
   1: multiply(factor=2) / multiply(factor=2) / multiply(factor=2)
      │
      ▼ a
   2: plus  
```

### CODE REVIEW

**Comment by wuhu** [comment]
Looks good - while we're at it, two suggestions:
- For consistency, I think `2: plus` should get three little incoming arrows
- I think it would be a bit nicer if we used the proper "corner" characters instead of  `__│ `.

**Comment by jasonkhadka** [comment]
those sounds good. i will update those things.

**Comment by jasonkhadka** [comment]
@wuhu  
New arrows for parallel
```
      ││││└───────────────────────────────────────────────────────────────────────────────┐
      │││└───────────────────────────────────────────────────────────┐                    │
      ││└───────────────────────────────────────┐                    │                    │
      │└───────────────────┐                    │                    │                    │
      │                    │                    │                    │                    │
      ▼ arg                ▼ arg                ▼ arg                ▼ arg                ▼ arg
   0: multiply(factor=2) / multiply(factor=2) / multiply(factor=2) / multiply(factor=2) / multiply(factor=2)
      │                    │                    │                    │                    │
      ▼ arg                ▼ arg                ▼ arg                ▼ arg                ▼ arg
   1: multiply(factor=2) / multiply(factor=2) / multiply(factor=2) / multiply(factor=2) / multiply(factor=2)
      |                    │                    │                    │                    │
      │┌───────────────────┘                    │                    │                    │
      ││┌───────────────────────────────────────┘                    │                    │
      │││┌───────────────────────────────────────────────────────────┘                    │
      ││││┌───────────────────────────────────────────────────────────────────────────────┘ 
      ▼▼▼▼▼ arg
   2: plus  
```

**Comment by sjrl** [comment]
Nice! This looks really good.

**Review by sjrl — APPROVED** [review]

**Review by wuhu — APPROVED** [review]

**Pull request merged**
