### PR TITLE
release process description

### PR DESCRIPTION
**Pull request by blythed**
## Description

Release process #327

### CODE REVIEW

**Comment by sjrl** [comment]
Looks good!

**Review by sjrl — APPROVED** [review]

**Review by wuhu — APPROVED** [review]
nice

**Comment by jasonkhadka** [comment]
👍

**Comment by jasonkhadka** [comment]
There is a github action for pypi-publish 
https://github.com/marketplace/actions/pypi-publish
with 
```
if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
```

We can trigger the publish when a commit is tagged. So, only thing for publication that needs to be done is update the version, tag the commit and rest could be automated.

**Pull request merged**
