### PR TITLE
Remove first marker

### LINKED ISSUE #404: Debugger marker arrow not holding for composes with parallel or rollout preprocesses
## 🐞 Bug

There is a bug on the marker arrow at the highest level of the debugger when we are handling `Compose`s whose preprocess part is a `Parallel` or a `Rollout`.

When executing the debugger, the first level shows the entire transform we are applying and an arrow pointing to the step that is caused the exception. 

For example, let `t0` be the transform:
```
t0 = (transform(lambda x: torch.LongTensor(x))
    >> batch
    >> transform(torch.nn.Embedding)(10, 8)
    >> transform(torch.nn.Linear(6, 4)
)
```
When executing `t0`, an error is going to occur at the step 3 since the shapes are not matching. Then, if we call the debugger, its first level is going to show
```
 Compose - "t0":

      │
      ▼ x
   0: lambda x: torch.LongTensor(x)                
      │
      ▼ args
   1: Batchify(dim=0)                              
      │
      ▼ input
   2: Embedding(num_embeddings=10, embedding_dim=8)
      │
      ▼ input
   3: Linear(in_features=6, out_features=4)          <---- error here 
```
The way we determine where to put the arrow `<---- error here` in `Compose`s is done (when the `Compose` fails in the forward step, like here) by computing
```
len(t0.pd_preprocess) + index_that_failed_on_the_forward = 2 + 1= 3
```
When the preprocess part is a `Rollout` or a `Parallel` another logic is applied. For example, let `t1` be 
```
to_tensor = transform(torch.LongTensor(x)
prep = (to_tensor >> batch) / (to_tensor >> batch)
t1 = (prep
    >> transform(torch.nn.Embedding)(10, 8) / identity
    >> transform(torch.nn.Linear)(6, 4) / identity
)
```
This is failing on the step 2 of the transform. For example, after executing `t1.infer_apply(([9, 8, 8], [1]))` and calling the debugger, we get this
```
Compose - "t1":

      │└──────────────────────────────────────────────┐
      │                                               │
      ▼ args                                          ▼ args
   0: [to_tensor >> Batchify(dim=0)] / [to_tensor >> Batchify(dim=0)]
      │                                               │
      ▼ input                                         ▼ args
   1: Embedding(num_embeddings=10, embedding_dim=8) / Identity()                    
      │                                               │
      ▼ input                                         ▼ args
   2: Linear(in_features=6, out_features=4)         / Identity()                      <---- error here
```
The way we compute  where the arrow points in this case (when the whole transform is a `Compose` and `pd_preprocess` is a `Parallel` or a `Rollout`) is by computing
```
1 + index_that_fails_on_the_forward = 1 + 1
```
This is the way we had been doing but there is a lack of generality on this criterium. It is when the transform is a `Compose`, the `preprocess` is a `Parallel` or `Rollout`, and the preprocess and forward are mixed on the same step of the transform. For example, let `t2` be
```
data_pipeline = to_tensor >> batch >> transform(torch.nn.Embedding)(10, 8) >> transform(torch.nn.Linear)(6, 4)
target_pipeline = to_tensor >> batch
t2 = (data_pipeline / target_pipeline) >> transform(torch.nn.CrossEntropyLoss)()
```
Now, if we execute `t2` (which fails on the linear layer) and call the debugger we get 
```
Compose - "t":

      │└────────────────────────┐
      │                         │
      ▼ args                    ▼ args
   0: [data_pipeline: ..>>..] / [to_tensor >> Batchify(dim=0)]
      │
      ▼ (input, target)
   1: CrossEntropyLoss()       <---- error here 
```
Why is it not pointing to 0 like expected? It is because the previous logic made for`t1` does not hold anymore. According to the previous rule, we failing step should be
```
1 + index_that_fails_on_the_forward = 1 + 0
```
since `t2.pd_forward` is
```
Compose:

      │└──────────────────────────────────────────────┐
      │                                               │
      ▼ args                                          ▼ args
   0: [<anonymous Embedding> >> <anonymous Linear>] / Identity()
      │
      ▼ (input, target)
   1: CrossEntropyLoss()
```
Then, the rule applied for `t1` is not correct here. We shouldn't sum 1 to the failing index on the forward, but 0. 

However, it's difficult to hold the cases for `t1`  and `t2` at the same time. We would need to check if the preprocess part and forward are mixed a same item of a `Compose`, which is not straightforward.

### PR DESCRIPTION
**Pull request by eramdiaz**
## Description
Fixes #404 and #340 by not showing anymore the arrow at the highest level of the debugger (where the entire transform we are executing is shown).

For example, let `t` be
```
t = (transform(lambda x: torch.LongTensor(x))
     >> batch
     >> transform(torch.nn.Embedding)(10, 8)
     >> transform(torch.nn.Linear)(6, 4)
)
```
Then, an error will be produced at the linear layer due to mismatching shapes. If we execute and call the debugger, at the first level we will get 
```
Compose - "t":

      │
      ▼ x
   0: lambda x: torch.LongTensor(x)                
      │
      ▼ args
   1: Batchify(dim=0)                              
      │
      ▼ input
   2: Embedding(num_embeddings=10, embedding_dim=8)
      │
      ▼ input
   3: Linear(in_features=6, out_features=4)      
```
as we see with no marker arrow. The deeper levels will already provide the marker arrow.  For example, the next one is
```

Compose:

      │
      ▼ input
   0: Embedding(num_embeddings=10, embedding_dim=8)
      │
      ▼ input
   1: Linear(in_features=6, out_features=4)          <---- error here 
```

### CODE REVIEW

**Comment by wuhu** [comment]
Why did you decide to remove the top level marker?

**Comment by eramdiaz** [comment]
This is supposed to solve the issue #404 (and #340), which describes a bug on the top level marker in a non edgy case. It is not a direct fix but I don't know how to solve it in a direct way. Let me know if you agree with the fix @wuhu :)

**Comment by eramdiaz** [comment]
This is supposed to solve the issue #404 (and #340), which describes a bug on the top level marker in a non edgy case. It is not a direct fix but I don't know how to solve it in a direct way. Let me know if you agree with the fix @wuhu :)

**Comment by wuhu** [comment]
@eramdiaz I got that, I was trying to understand why you want to remove the marker entirely on the top level, rather than making it work in those cases - Is it not possible to fix it in a direct way or do you think it's too complicated / not worth the effort?

**Pull request merged**
