### PR TITLE
Notebooks in Colab

### LINKED ISSUE #324: Add notebooks to Google Colab
## Description

Add jupyter notebooks in `notebooks` to google colab for easy sharing. Create a link to the google colab in the README. 

## Solution

- [x] Add the notebooks to the shared google drive
- [x] set up correct permissions

## Alternative
Use this kind of link https://colab.research.google.com/github/lf1-io/padl/ which can be made into a badge as well
[Open In Colab](https://colab.research.google.com/github/lf1-io/padl/)
```python
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/lf1-io/padl/)
```
to directly prompt users to open our notebooks into their own google colab environment. Explained here: https://github.com/weiji14/deepbedmap/issues/61
- [x] Make sure notebooks can be directly run (including installing all dependencies)
- [ ] Update the pypi artifact to include a version of PADL that supports python 3.7
- [x] Add Colab badge to README

### PR DESCRIPTION
**Pull request by sjrl**
## Description

Fixes #324

### CODE REVIEW

**Comment by sjrl** [comment]
Confirmed run on Colab w/ GPU
- [ ] MNIST example
- [ ] NLP example
- [ ] Sentiment analysis

**Comment by sjrl** [comment]
> Seems like installation of Padl to colab was removed? There seems to be a virtual env `tenen_env` but I am getting: `Unrecognized runtime "tenen_env"; defaulting to "python3"` And `ModuleNotFoundError: No module named 'padl'`

Ahh make sure when you click the Colab badge that you select the `notebook_update_new` branch. It defaults to the `main` which doesn't have any of the new changes.

**Comment by jasonkhadka** [comment]
ah yeah that was the problem!

**Comment by jasonkhadka** [comment]
Looks good! 👍

**Pull request merged**
